import test from 'node:test';
import assert from 'node:assert/strict';
import {prefillInvoice,makeUpdatePayload,editTotals} from '../app/js/edit.js';
import {ERP} from '../app/js/erp.js';
import config from '../app/config.json' with {type:'json'};
const invoice={invoice_id:'1234567890123456789',invoice_number:'INV-9',customer_id:'c1',customer_name:'Customer',date:'2026-09-17',payment_terms:30,due_date:'2026-10-17',salesperson_id:'s1',place_of_supply:'KL',gst_no:'GST',notes:'Keep me',adjustment:.31,discount:'5%',discount_type:'entity_level',is_discount_before_tax:true,is_inclusive_tax:false,billing_address:{city:'Kochi'},shipping_address:{city:'Thrissur'},custom_fields:[{customfield_id:'unmapped',value:'preserve'}],line_items:[{line_item_id:'999999999999999999',item_id:'i1',name:'Set',quantity:12,rate:100,tax_id:'t1',tax_percentage:18,tax_name:'GST',description:'Keep line',item_custom_fields:[{customfield_id:'linecf',value:4}],salesorder_item_id:'so1'}]};
const masters={i1:{name:'Set',cf_m_unit:'SET',cf_ratio:3}};
function fixture(){return prefillInvoice(structuredClone(invoice),masters,config);}
test('prefill maps invoice snapshot, addresses, business fields and piece quantities',()=>{const s=fixture();assert.equal(s.customer.contact_id,'c1');assert.equal(s.customer.shipping_address.city,'Thrissur');assert.equal(s.values.invoice_number,'INV-9');assert.equal(s.values.discount,5);assert.equal(s.values.adjustment,.31);assert.equal(s.values.notes,'Keep me');assert.equal(s.lines[0].quantity,4);assert.equal(s.lines[0].rate,100);assert.equal(s.values.salesperson_id,'s1');});
test('unchanged update round-trips line quantities, IDs, taxes, links and custom fields',()=>{const s=fixture(),p=makeUpdatePayload(s,s.values,config);assert.equal(p.line_items[0].line_item_id,invoice.line_items[0].line_item_id);assert.equal(p.line_items[0].quantity,12);assert.equal(p.line_items[0].rate,100);assert.equal(p.line_items[0].salesorder_item_id,'so1');assert.equal(p.line_items[0].description,'Keep line');assert.deepEqual(p.custom_fields,invoice.custom_fields);assert.deepEqual(p.billing_address,invoice.billing_address);assert.equal(p.adjustment,.31);assert.equal(p.due_date,invoice.due_date);assert.equal(p.invoice_id,undefined);});
test('edited order quantity sends pieces; new items have no line ID; deleted IDs absent',()=>{const s=fixture();s.lines[0].quantity=5;s.lines.push({item_id:'i2',quantity:2,pieces:1,rate:50,tax:s.lines[0].tax});let p=makeUpdatePayload(s,s.values,config);assert.equal(p.line_items[0].quantity,15);assert.equal(p.line_items[1].line_item_id,undefined);s.lines.shift();p=makeUpdatePayload(s,s.values,config);assert.equal(p.line_items.length,1);assert.equal(p.line_items[0].item_id,'i2');});
test('order mode divides ERP pack rate and round-trips without doubling',()=>{const c={...config,invoiceQuantityMode:'order'},s=prefillInvoice(invoice,masters,c);assert.equal(s.lines[0].quantity,12);assert.equal(s.lines[0].rate,100/3);assert.equal(makeUpdatePayload(s,s.values,c).line_items[0].rate,100);});
test('inclusive tax and editable line discounts preserve invoice tax mode',()=>{const i={...invoice,is_inclusive_tax:true,discount_type:'item_level',line_items:[{...invoice.line_items[0],rate:118,discount:'10%'}]},s=prefillInvoice(i,masters,config);const t=editTotals(s.lines,s.values,i);assert.equal(t.subtotal,1200);assert.equal(t.discount,120);assert.equal(t.tax,194.4);s.lines[0].discount='5%';const p=makeUpdatePayload(s,s.values,config);assert.equal(p.is_inclusive_tax,true);assert.equal(p.discount_type,'item_level');assert.equal(p.line_items[0].discount,'5%');});
test('mapped delivery values prefill and clearing retains unrelated fields',()=>{const c={...config,customFields:{transport:{id:'unmapped'}}},s=prefillInvoice(invoice,masters,c);assert.equal(s.values.custom.transport,'preserve');s.values.custom.transport='';assert.equal(makeUpdatePayload(s,s.values,c).custom_fields[0].value,'');});
function api(sdk){const a=new ERP({apiBase:'https://www.zohoapis.in/erp/v3',organizationId:'org',connectionLinkName:'erp_admin'},sdk);a.ready=true;return a;}
test('ID-only context fetches full invoice and PUT never posts or emails',async()=>{const calls=[];const a=api({get:async key=>{assert.equal(key,'invoice');return {invoice:{invoice_id:invoice.invoice_id}};},request:async o=>{calls.push(o);return {code:0,invoice};}});assert.equal((await a.currentInvoice()).invoice_id,invoice.invoice_id);const s=fixture();await a.updateInvoice(invoice.invoice_id,makeUpdatePayload(s,s.values,config));assert.deepEqual(calls.map(c=>c.method),['GET','PUT']);assert.ok(calls[1].url.endsWith('/invoices/'+invoice.invoice_id));assert.ok(calls[1].url_query.some(q=>q.key==='send'&&q.value==='false'));});
test('missing context and ERP rejection surface actionable errors',async()=>{await assert.rejects(()=>api({get:async()=>({})}).currentInvoice(),/No invoice context/);await assert.rejects(()=>api({request:async()=>({code:14,message:'Invoice locked by approval'})}).updateInvoice('1',{}),e=>e.apiRejected&&e.message==='Invoice locked by approval');});
test('refresh attempts all three shapes and then allowed top reload',async()=>{const calls=[];let reloaded=false;globalThis.window={top:{location:{reload(){reloaded=true;}}}};const a=api({invoke:async(...args)=>{calls.push(args);throw Error('unsupported');}});assert.equal(await a.refreshInvoices(),true);assert.deepEqual(calls,[['REFRESH_DATA','invoice'],['REFRESH_DATA',{entity:'invoice'}],['REFRESH_DATA']]);assert.equal(reloaded,true);globalThis.window={get top(){throw Error('cross origin');}};assert.equal(await a.refreshInvoices(),false);delete globalThis.window;});
test('resize clamps to small host viewport and handles denied resize',async()=>{globalThis.window={top:{innerWidth:390,innerHeight:500}};let size;const a=api({extension:{init:async()=>{}},get:async()=>({organization:{organization_id:'org'}}),invoke:async(_,v)=>{size=v;throw Error('denied');}});await a.init();assert.deepEqual(size,{width:'350px',height:'410px'});delete globalThis.window;});
